[colors]
trans = #00000000
semi-trans-black = #cc000000
shade-1 = #32344a
shade-2 = #444b6a
shade-3 = #787c99
shade-4 = #CACACE
shade-5 = #acb0d0
focus = #3f3f3f
background = #1f1f1f
foreground = #eee
red        = #ff5555
bloodofmyenemies = #a60b00
green      = #50fa7b
yellow     = #f1fa8c
blue       = #6272a4
purple     = #bd93f9
cyan       = #8be9fd
orange     = #ff5555
pink       = #ff79c6
grey = #8fa6a1




[bar/top]
width  = 100%
height = 19 

monitor-strict = false
override-redirect = false
bottom = false
separator = |
radius = 6 
fixed-center = true

background = ${semi-trans-black}
foreground = ${colors.grey}

line-size  = 1 
line-color = ${colors.foreground}

border-size  = 0
border-color = ${colors.background}

padding-left  = 0
padding-right = 0

module-margin-left  = 0.3  
module-margin-right = 0.3 

; Font
font-0 = Hack Nerd Font:size=10;2
font-1 = "UbuntuMono Nerd Font:size=16;3"
font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=8;1"
font-3 = "Font Awesome 5 Free:style=Solid:pixelsize=8;1"
font-4 = "Font Awesome 5 Brands:pixelsize=8;1"



; Modules
modules-left   = i3 
modules-center = time
modules-right  = date audio network battery 


[module/i3]
type = internal/i3
pin-workspaces = true
; Default: false
; New in version 3.6.0
show-urgent = true

; Sort
index-sort = true

; Create click handler used to focus workspace
; Default: true
enable-click = false

; Create scroll handlers used to cycle workspaces
; Default: true
enable-scroll = false

; Display icons
fuzzy-match = true

; Icons
ws-icon-0       = 1;
ws-icon-1       = 2;
ws-icon-2       = 3;
ws-icon-3       = 4;
ws-icon-4       = 5;
ws-icon-5       = 6;
ws-icon-default = 

; Focused label
label-focused            = %icon%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.focus} 
label-focused-underline = ${colors.green}
label-focused-padding    = 2

; Unfocused labels
label-unfocused         = %icon%
label-unfocused-padding = 2 

; Visible labels
label-visible         = %icon%
label-visible-padding = 2 

; Urgent labels
label-urgent            = %icon%
label-urgent-foreground = ${colors.red}
label-urgent-padding    = 2 

bar-used-width = 5
bar-used-foreground-0 = #aaff77
bar-used-foreground-1 = #aaff77
bar-used-foreground-2 = #fba922
bar-used-foreground-3 = #ff5555
bar-used-indicator = |
bar-used-indicator-font = 6
bar-used-indicator-foreground = #ff
bar-used-fill = ─
bar-used-fill-font = 6
bar-used-empty = ─
bar-used-empty-font = 6
bar-used-empty-foreground = #444444

;[module/weather]
;type = custom/script
#exec = ~/.config/polybar/scripts/weather.sh

; Update interval
interval = 600

; Label
label         = %output%
label-padding = 1

;----------------time--------------
; click-middle =
[module/time]
type = internal/date
; Update interval
interval = 1.0
; Format
;time = %%{F#fff}%H:%M:%S%%{F-}
time = %%{F#fff}%H:%M%%{F-}
; Label
;label         =  %time%
label         = %time%
label-padding = 1

;--------------data---------------

[module/date]
type = internal/date
; Update interval
interval = 1.0
; Format
date = %%{F#fff}%d-%m-%Y%%{F-} 
; Label
label         =  %date%
label-padding = 1


;---------------memory-----------
;[module/memory]
;type = internal/memory
;interval = 1
; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
;label = %percentage_used%%

;format = Mem <label>
;format-prefix = " "
;format-prefix-foreground = #fefefe
;format-foreground = #fefefe
;format-background = #668bd7








[module/audio]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
; Volume label
;label-volume  = %percentage%%
ramp-volume-0 =  
ramp-volume-1 = 
ramp-volume-2 =  

ramp-volume-foreground = ${colors.cyan}
label-volume-foreground = ${colors.cyan}
label-volume-padding    = 0 

; Muted label
label-muted            =  
label-muted-foreground = ${colors.red}
label-muted-padding    = 0 

[module/network]
type = internal/network

; Interface
interface = wlp3s0
;interface = wlo1

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true

; Consider an `UNKNOWN` interface state as up.
; Some devices like USB network adapters have 
; an unknown state, even when they're running
; Default: false
unknown-as-up = true


; Connected label
;label-connected            = 
;label-connected-foreground = ${colors.green}
;label-connected-padding    = 1 
; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
;format-connected = <ramp-signal> <label-connected>

; Available tags:
;   <label-disconnected> (default)
format-disconnected = <label-disconnected>

; Available tags:
;   <label-connected> (default)
;   <label-packetloss>
;   <animation-packetloss>
format-packetloss = <animation-packetloss> <label-connected>

; All labels support the following tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %netspeed%  [wireless+wired] (%upspeed% + %downspeed%) (New in version 3.6.0)
;   %linkspeed% [wired]
;   %mac%       [wireless+wired] (New in version 3.6.0)

; Default: %ifname% %local_ip%
label-connected =   %essid%%downspeed:9%
label-connected-foreground = ${colors.green} 
label-connected-padding    = 0 
; Default: (none)

label-disconnected            = 
label-disconnected-foreground = ${colors.red}
label-disconnected-padding    =0 
; Default: (none)
;label-packetloss = %essid%
;label-packetloss-foreground = #eefafafa

; Only applies if <ramp-signal> is used
;ramp-signal-0 =  
;ramp-signal-1 =  
;ramp-signal-2 = 
;ramp-signal-0-foreground = ${colors.green}
;ramp-signal-1-foreground = ${colors.green}
;ramp-signal-2-foreground = ${colors.green}

; Only applies if <animation-packetloss> is used
animation-packetloss-0 = ⚠
animation-packetloss-0-foreground = #ffa64c
animation-packetloss-1 = 📶
animation-packetloss-1-foreground = #000000
; Framerate in milliseconds
animation-packetloss-framerate = 500
; Disconnected label
;label-disconnected            = 
;label-disconnected-foreground = ${colors.red}
;label-disconnected-padding    = 1

[module/lock]
type = custom/text

; Label
content            = 
; content-foreground = ${colors.foreground}
content-padding    = 1
; Mouse click
click-left = i3lock-fancy -f Roboto-Regular -t ""

[module/logout]
type = custom/text

; Label
content            = 
; content-foreground = ${colors.foreground}
content-padding    = 1

; Mouse click
click-left = i3-msg exit

[module/poweroff]
type = custom/text
content            = 
content-foreground = ${colors.red}
content-padding    = 1
; Mouse click
click-left = poweroff

[settings]
screenchange-reload     = true
;compositing-background = xor
;compositing-foreground = source
;compositing-border     = over
;pseudo-transparency    = false

[global/wm]
margin-top    = 10
margin-bottom = 10

[module/consumption]
type = custom/script
exec = /home/irfash/.config/polybar/power.sh
interval = 2
[module/battery]
type = internal/battery
full-at = 98

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>

;label-charging = %percentage%% %time%h
;label-discharging = %percentage%% %time%h 

label-charging = %percentage%% 
label-discharging = %percentage%% 
ramp-capacity-0 = 
ramp-capacity-0-foreground = #f53c3c
ramp-capacity-1 = 
ramp-capacity-1-foreground = #ffa900
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

bar-capacity-width = 10
bar-capacity-format = %{+u}%{+o}%fill%%empty%%{-u}%{-o}
bar-capacity-fill = █
bar-capacity-fill-foreground = #ddffffff
bar-capacity-fill-font = 3
bar-capacity-empty = █
bar-capacity-empty-font = 3
bar-capacity-empty-foreground = #44ffffff

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

[module/cpu]
type = internal/cpu
interval = 0.5
format = <label> <ramp-coreload>
label = CPUb
